---
defaultCommands:
- name: restart
  allow: []
  scripts:
  - burndown
  - burnup
- name: burndown
  allow: []
  scripts:
  - burndown
- name: burnup
  allow: []
  scripts:
  - burnup
services:
- name: workflows
  basePath: "~/tapis-kube/workflows"
  useDefaultCommands: true
  useNameAsPath: true
  allow: ["proxy"]
  components:
  - name: api
  - name: engine
- name: proxy
  basePath: "~/tapis-kube/proxy"
  useDefaultCommands: true
  useNameAsPath: false
  components:
  - name: nginx
    basePath:
    path: nginx
    commands:
      newconfig:
      - newconfig
